### ISSUE TITLE
Appenders and Tailers can form a memory leak by keeping track of resources to close

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#315]

**Comment by amichair** [comment]
This is good for not letting the closers collection grow forever, but on the other hand it allows them to be claimed by GC without actually being closed (even on shutdown, as they were before)... I think they should be closed right before being removed from closers. Maybe they can be checked at some strategic points and just the unused ones closed and discarded, or maybe a ReferenceQueue can be used to release the resources after the weak references are gone. Or some better idea :-)

**Comment by amichair** [comment]
What do you think about this? I think it's a problem if now even when closing the queue things aren't getting released properly, since it breaks the workaround of restarting the queue once a day (which is what we're doing until a proper fix.) In that sense it was better to leave the closers list as it was.

**Comment by peter-lawrey** [comment]
Hmmm. I will have look at this tomorrow.

On 13 Dec 2016 12:59, "amichair" <notifications@github.com> wrote:

What do you think about this? I think it's a problem if now even when
closing the queue things aren't getting released properly, since it breaks
the workaround of restarting the queue once a day (which is what we're
doing until a proper fix.) In that sense it was better to leave the closers
list as it was.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/315#issuecomment-266732121>,
or mute the thread

**Comment by amichair** [comment]
Your thoughts?

**Comment by amichair** [comment]
Do you intend on solving the leaks? This is preventing us from upgrading since the workaround of restarting the queue doesn't work anymore (ugly as it may be, it allowed proper file deletion etc.).

A proper fix would be greatly appreciated, and important for considering Chronicle for a production system.

**Comment by peter-lawrey** [comment]
We intend to fix the leak.
There are times of the year when we are busier and have to focus on paid
support/consulting and times of the year we are freer and can do
speculative development. It can be hard to predict when we will be busier
as we have been for the last couple of weeks. Next week is looking busy as
well.


ᐧ

**Comment by oyvindgh** [comment]
Hi,

We are experiencing something similar as described here.
Our chronicle-queue is rolling on a daily basis, yyyymmdd.cq4. 
After a roll, previous days file descriptors are still open.

Has this issue been fixed in a newer version?
We are on version 4.5.24.

**Comment by peter-lawrey** [comment]
It is something we have improved but not fixed for all use cases I believe.

**Comment by oyvindgh** [comment]
Seems like our use case is fixed.
I tried with version 4.5.27 and here we do not have the problem anymore :)

Thanks!

**Comment by sergebg** [comment]
I can provide a kind of test:
```java
public class MemoryLeakDemo {
    public static void main(String[] args) throws InterruptedException {
        File file = Paths.get("target", "queue").toFile();
        System.out.println(file);
        try (SingleChronicleQueue queue = ChronicleQueueBuilder.single(file)
                .rollCycle(RollCycles.TEST_SECONDLY)
                .build()) {
            int lap = 0;
            while (true) {
                ExcerptAppender appender = queue.acquireAppender();
                System.out.println(String.format("%6d: %s", (++lap), appender));

                for (int i = 0; i < 1; i++) {
                    int value = i;
                    appender.writeBytes(wire -> wire.writeInt(value));
                }
                System.out.println(String.format(" index: %d", appender.lastIndexAppended()));
                appender = null;

                Thread.sleep(10_000);
                System.gc();
            }
        }
    }
}
```
While this demo is running the process will never close queue chunks, which can be expected using shell command
```bash
lost -p <pid> | grep target/queue
```
The issue could be fixed by adding finalize() method to StoreAppender. Or it could be delegated to the user code via Closeable interface.

**Comment by peter-lawrey** [comment]
The Store appender is being held when you call System.gc(); so finalise ()
might not help.

**Comment by sergebg** [comment]
Nobody holds them, because internally appenders are stored within WeakReference. And it's easy to check. Basically, "gc()" call is added here just to make it more deterministic. The test prints each time a new instance, and "lsof" shows how the number of leaked file descriptors is increased with each iteration. Having applied the fix you will find only 2 open file descriptors.

Output (slightly reduced)
```
    10: <...>SingleChronicleQueueExcerpts$StoreAppender@6ea6d14e
    11: <...>SingleChronicleQueueExcerpts$StoreAppender@6ad5c04e
    12: <...>SingleChronicleQueueExcerpts$StoreAppender@6833ce2c
```

And that is example of lsof output with the fix applied. Any time there are only 2 lines. In the original version files are not closed, because it does not hold references to underlying resources.
```
xgate% lsof -p 9885 | grep target/queue 
java    9885 sergey  txt     REG                1,8  83886080 42186930 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080634.cq4
java    9885 sergey   50u    REG                1,8  83886080 42186930 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080634.cq4
xgate% lsof -p 9885 | grep target/queue 
java    9885 sergey  txt     REG                1,8  83886080 42186933 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080644.cq4
java    9885 sergey   50u    REG                1,8  83886080 42186933 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080644.cq4
xgate% lsof -p 9885 | grep target/queue 
java    9885 sergey  txt     REG                1,8  83886080 42186933 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080644.cq4
java    9885 sergey   50u    REG                1,8  83886080 42186933 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080644.cq4
xgate% lsof -p 9885 | grep target/queue 
java    9885 sergey  txt     REG                1,8  83886080 42186937 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080654.cq4
java    9885 sergey   50u    REG                1,8  83886080 42186937 /Users/sergey/Projects/Chronicle-Queue/target/queue/20170501-080654.cq4
```

**Comment by scottkidder** [comment]
Can we close this in favor of #357?

**Comment by dpisklov** [comment]
Fixed in #357
